--- 
- hosts: mywebservers
  user: ansible
  become: yes
  tasks:
    - name: install the java on ubuntu
      apt:
        name: "{{myjavaOnUbuntu}}"
        state: present 
      when: ansible_os_family == "Debian"
    - name: install the java on RedHat
      yum: 
        name: "{{myjavaOnRedHat}}"
        state: present
      when: ansible_os_family == "RedHat"